In [0]:
import numpy as np

## 1. 1차원 정렬

1차원 정렬은 매우 간단합니다.

In [0]:
arr = np.array([1, 10, 5, 8, 2, 4, 3, 6, 8, 7, 9])

In [0]:
arr

np.sort(arr)

In [0]:
np.sort(arr)

기본적으로 오름차순 정렬을 수행합니다.

In [0]:
np.sort(arr)[::-1]

내림차순 정렬은 옵션에 -1 값을 주면됩니다.

하지만, 이 값들은 **유지가 되지 않습니다**!

값을 sort 된 상태로 저장하려면, 배열 자체에 sort를 해줄 수 있습니다.

In [0]:
np.sort(arr)

In [0]:
arr2 = np.sort(arr)

In [0]:
arr

In [0]:
arr2

In [0]:
arr.sort()

In [0]:
arr

## 2. N차원 정렬

In [0]:
arr2d = np.array([[5, 6, 7, 8], 
                  [4, 3, 2, 1],
                  [10, 9, 12, 11]])

In [0]:
arr2d.shape

In [0]:
arr2d

### 2-1. 열 정렬 (왼쪽에서 오른쪽으로)

In [0]:
arr2d

In [0]:
np.sort(arr2d, axis=1)

### 2-2. 행 정렬 (위에서 아래로)

In [0]:
arr2d

In [0]:
np.sort(arr2d, axis=0)

## 3. index를 반환하는 argsort

정렬된 값을 반환하는 것이 아닌 index를 반환합니다.

In [0]:
arr2d = np.array([[5, 6, 7, 8], 
                  [4, 3, 2, 1],
                  [10, 9, 12, 11]])


### 3-1. 열 정렬 (왼쪽에서 오른쪽으로)

In [0]:
np.argsort(arr2d, axis=1)

array([[0, 1, 2, 3],
       [3, 2, 1, 0],
       [1, 0, 3, 2]])

### 3-2. 행 정렬

In [0]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

In [0]:
np.sort(arr2d, axis=0)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

In [0]:
np.argsort(arr2d, axis=0)

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [2, 2, 2, 2]])