In [0]:
import numpy as np

## 1. 행렬 - 덧셈

### 1-1. 덧셈

In [0]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [0]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [0]:
a + b

In [0]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [0]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [0]:
a + b

### 1-2. Sum

In [0]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [0]:
np.sum(a, axis=0)

In [0]:
np.sum(a, axis=1)

## 2. 행렬 - 뺄셈

In [0]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [0]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [0]:
a - b

In [0]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [0]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [0]:
a - b

## 3. 곱셈

일반 곱셈

In [0]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [0]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [0]:
a.shape, b.shape

((2, 3), (2, 3))

In [0]:
a * b

array([[ 3,  8, 15],
       [ 2,  6, 12]])

단순 곱셈과 dot product는 다릅니다. 이점 유의하세요!

In [0]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [0]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [0]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [0]:
a * b

array([[ 3,  8, 15],
       [ 2,  6, 12]])

In [0]:
a = np.array([[1, 2, 3],
              [1, 2, 3], 
              [2, 3, 4]])

In [0]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [0]:
a.shape, b.shape

((3, 3), (3, 2))

In [0]:
np.dot(a, b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [0]:
a.dot(b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [0]:
1*1 + 2*3 + 3*5

In [0]:
1*2 + 2*4 + 3*6