In [0]:
import numpy as np

## 1. Broadcasting

## 1-1. 숫자의 연산 (단일)

In [0]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [0]:
b = np.array([[3, 3, 3], 
              [3, 3, 3]])

In [0]:
a + b

array([[4, 5, 6],
       [5, 6, 7]])

In [0]:
a + 3

array([[4, 5, 6],
       [5, 6, 7]])

In [0]:
a - 3

array([[-2, -1,  0],
       [-1,  0,  1]])

In [0]:
a * 3

array([[ 3,  6,  9],
       [ 6,  9, 12]])

In [0]:
a / 3

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 1.        , 1.33333333]])

### 1-2. array(배열)의 브로드캐스팅

오리지널 array의 shape가 유지됨을 잘 보세요

In [0]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [0]:
b = np.array([[1], 
              [2]])

In [0]:
a.shape, b.shape

In [0]:
a * b

In [0]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [0]:
b = np.array([1, 2, 3])

In [0]:
a * b